projects:
  CarrierCommand:
    schemaPath: amplify/backend/api/CarrierCommand/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-2
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
